# Generated by Django 6.0 on 2025-12-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(help_text='Nível de 0 a 100')),
                ('cor', models.CharField(default='#3498db', help_text='Cor em hexadecimal (ex: #3498db)', max_length=7)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'ordering': ['-nivel', 'ordem'],
            },
        ),
    ]
