# Generated by Django 6.0 on 2025-12-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icone',
            field=models.CharField(default='fa-solid fa-code', help_text='Classe do ícone (ex: fa-brands fa-python, devicon-java-plain)', max_length=50),
            preserve_default=False,
        ),
    ]
