# Generated by Django 6.0 on 2025-12-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_skill_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(help_text='Nível de 0 a 100')),
                ('cor', models.CharField(default='#3498db', help_text='Cor em hexadecimal (ex: #3498db)', max_length=7)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('icone', models.CharField(default='fa-solid fa-code', help_text='Classe do ícone (ex: fa-brands fa-python, devicon-java-plain)', max_length=60)),
            ],
            options={
                'ordering': ['-nivel', 'ordem'],
            },
        ),
        migrations.AlterField(
            model_name='skill',
            name='icone',
            field=models.CharField(default='fa-solid fa-code', help_text='Classe do ícone (ex: fa-brands fa-python, devicon-java-plain)', max_length=60),
        ),
    ]
