# Generated by Django 6.0 on 2025-12-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill_2_alter_skill_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='projetos/')),
                ('tecnologias', models.CharField(max_length=200)),
                ('link_github', models.URLField(blank=True)),
                ('link_demo', models.URLField(blank=True)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateField()),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
