# Generated by Django 6.0 on 2025-12-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tecnologia_remove_projeto_tecnologias'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(to='core.tecnologia'),
        ),
    ]
