# Generated by Django 6.0 on 2025-12-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projeto_tecnologias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(default='fa-solid fa-code', help_text='Classe do ícone (ex: fa-brands fa-python, devicon-java-plain)', max_length=50),
        ),
    ]
