# Generated by Django 6.0 on 2026-01-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icone',
            field=models.CharField(default='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/code/code-original.svg', help_text='URL do ícone (SVG/PNG)', max_length=255),
        ),
    ]
