# Generated by Django 6.0 on 2026-01-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_skill_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill_2',
            name='icone',
            field=models.CharField(default='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/code/code-original.svg', help_text='URL do ícone (SVG/PNG)', max_length=255),
        ),
    ]
