# Generated by Django 6.0 on 2026-01-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_tecnologia_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(help_text='Nível de 0 a 100')),
                ('cor', models.CharField(default='#3498db', help_text='Cor em hexadecimal (ex: #3498db)', max_length=7)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('icone', models.CharField(default='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/code/code-original.svg', help_text='URL do ícone (SVG/PNG)', max_length=255)),
            ],
            options={
                'ordering': ['-nivel', 'ordem'],
            },
        ),
    ]
