# Generated by Django 6.0 on 2026-01-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_banco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='titulo',
        ),
        migrations.AddField(
            model_name='projeto',
            name='descricao_pt',
            field=models.TextField(default='', verbose_name='Descrição en'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='titulo_en',
            field=models.CharField(default='', max_length=200, verbose_name='Titulo pt'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='titulo_pt',
            field=models.CharField(default='', max_length=200, verbose_name='Titulo pt'),
        ),
    ]
