# Generated by Django 6.0 on 2026-01-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_projeto_descricao_remove_projeto_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='descricao_en',
            field=models.TextField(default='', verbose_name='Descrição en'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao_pt',
            field=models.TextField(default='', verbose_name='Descrição pt'),
        ),
    ]
