# Generated by Django 6.0 on 2026-01-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_projeto_descricao_en_alter_projeto_descricao_pt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='descricao_en',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='descricao_pt',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='titulo_en',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='titulo_pt',
        ),
    ]
