# Generated by Django 6.0 on 2026-01-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_projeto_descricao_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(default='Descrição'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(default='Título', max_length=200),
        ),
    ]
