# Generated by Django 6.0 on 2026-01-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_projeto_descricao_projeto_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='descricao_en',
            field=models.TextField(blank=True, default='Description'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='titulo_en',
            field=models.CharField(blank=True, default='Title', max_length=200),
        ),
    ]
