# Generated by Django 6.0 on 2026-01-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_projeto_descricao_en_projeto_titulo_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.URLField(help_text='URL da imagem do projeto (GitHub RAW, Cloudinary, etc)'),
        ),
    ]
